[build]
  command = "ng build --prod"
  functions = "./functions"
  publish = "dist"
[dev]
  command = "npm run start"
  functions = "./functions"
  publish = "src"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
