[build]
  command = "npm run build:ssr"
  functions = "./functions"
  publish = "dist/andiamo/browser"
[dev]
  command = "npm run start"
  functions = "./functions"
  publish = "src"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200